### ISSUE TITLE
I need to rip out the utility functionality and move it to the UserApi 

### ISSUE THREAD

**Issue by paustian** [paustian/Quickcheck#17]
I have a bunch of processing code in the UserController function because I was being lazy (bad programmer!) I need to take this out and put it in a repository class so that I can call it from the controller as well as the hook handler to render a quiz appropriately. I hope I learned my lesson.

**Comment by craigh** [comment]
not Api - you mean Repository?

**Comment by paustian** [comment]
Yep. Repository. Clearly the place to put it.

**Comment by paustian** [comment]
Code moved and functionality working
